name: stroke_predictor_app
description: MVP for Stroke Type Prediction (Offline)
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
